### PR TITLE
Update the Makefile and added the scripts

### PR DESCRIPTION
**Pull request by praveenkumar**

### CODE REVIEW

**Comment by gbraad** [comment]
After these changes, Docker fails:

```
Setting Docker configuration on the remote daemon...                                                                                                                                                                                                                                                                       
(minishift) Calling .GetSSHHostname                                                                                                                                                                                                                                                                                        
(minishift) DBG | GetIP called for minishift                                                                                                                                                                                                                                                                               
(minishift) DBG | Failed to retrieve dnsmasq leases from /var/lib/libvirt/dnsmasq/docker-machines.leases                                                                                                                                                                                                                   
(minishift) DBG | IP address: 192.168.42.13                                                                                                                                                                                                                                                                                
(minishift) DBG | Unable to locate IP address for MAC 52:54:00:2f:1d:b3                                                                                                                                                                                                                                                    
(minishift) Calling .GetSSHPort                                                                                                                                                                                                                                                                                            
(minishift) Calling .GetSSHKeyPath                                                                                                                                                                                                                                                                                         
(minishift) DBG | AK: resolvestorepath: /home/gbraad/.minishift                                                                                                                                                                                                                                                            
(minishift) Calling .GetSSHKeyPath                                                                                                                                                                                                                                                                                         
(minishift) DBG | AK: resolvestorepath: /home/gbraad/.minishift                                                                                                                                                                                                                                                            
(minishift) Calling .GetSSHUsername                                                                                                                                                                                                                                                                                        
Using SSH client type: external                                                                                                                                                                                                                                                                                            
Using SSH private key: /home/gbraad/.minishift/machines/minishift/id_rsa (-rw-------)                                                                                                                                                                                                                                      
&{[-F /dev/null -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none docker@192.168.42.13 -o IdentitiesOnly=yes -i /home/gbraad/.minishift/machines/minishift/id_rsa -p 22] /usr
/bin/ssh <nil>}                                                                                                                                                                                                                                                                                                            
About to run SSH command:                                                                                                                                                                                                                                                                                                  
sudo mkdir -p /etc/systemd/system/docker.service.d && printf %s "[Service]                                                                                                                                                                                                                                                 
ExecStart=
ExecStart=/usr/bin/dockerd-current -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock \
           --selinux-enabled \
           --log-driver=journald \
           --signature-verification=false \
           --add-runtime docker-runc=/usr/libexec/docker/docker-runc-current \
           --default-runtime=docker-runc \
           --exec-opt native.cgroupdriver=systemd \
           --userland-proxy-path=/usr/libexec/docker/docker-proxy-current \
           --default-runtime=docker-runc \                                                                                                                                                                                                                                                                                 
           --exec-opt native.cgroupdriver=systemd \                                                                                                                                                                                                                                                                        
           --userland-proxy-path=/usr/libexec/docker/docker-proxy-current \                                                                                                                                                                                                                                                
           --storage-driver overlay2 --tlsverify --tlscacert /etc/docker/ca.pem \                                                                                                                                                                                                                                          
           --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem \                                                                                                                                                                                                                                          
           --label provider=kvm --insecure-registry 10.0.75.1 --insecure-registry 172.30.0.0/16 --registry-mirror http://10.0.75.1:5000                                                                                                                                                                                    
Environment=                                                                                                                                                                                                                                                                                                               
" | sudo tee /etc/systemd/system/docker.service.d/10-machine.conf                                                                                                                                                                                                                                                          
SSH cmd err, output: <nil>: [Service]                                                                                                                                                                                                                                                                                      
ExecStart=                                                                                                                                                                                                                                                                                                                 
ExecStart=/usr/bin/dockerd-current -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock            --selinux-enabled            --log-driver=journald            --signature-verification=false            --add-runtime docker-runc=/usr/libexec/docker/docker-runc-current            --default-runtime=docker-runc      
      --exec-opt native.cgroupdriver=systemd            --userland-proxy-path=/usr/libexec/docker/docker-proxy-current            --storage-driver overlay2 --tlsverify --tlscacert /etc/docker/ca.pem            --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem            --label provider=kvm --in
secure-registry 10.0.75.1 --insecure-registry 172.30.0.0/16 --registry-mirror http://10.0.75.1:5000                                                                                                                                                                                                                        
Environment=                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                           
(minishift) Calling .GetSSHHostname                                                                                                                                                                                                                                                                                        
(minishift) DBG | GetIP called for minishift                                                                                                                                                                                                                                                                               
(minishift) DBG | Failed to retrieve dnsmasq leases from /var/lib/libvirt/dnsmasq/docker-machines.leases                                                                                                                                                                                                                   
(minishift) DBG | IP address: 192.168.42.13                                                                                                                                                                                                                                                                                
(minishift) DBG | Unable to locate IP address for MAC 52:54:00:2f:1d:b3                                                                                                                                                                                                                                                    
(minishift) Calling .GetSSHPort                                                                                                                                                                                                                                                                                            
(minishift) Calling .GetSSHKeyPath                                                                                                                                                                                                                                                                                         
(minishift) DBG | AK: resolvestorepath: /home/gbraad/.minishift                                                                                                                                                                                                                                                            
(minishift) Calling .GetSSHKeyPath                                                                                                                                                                                                                                                                                         
(minishift) DBG | AK: resolvestorepath: /home/gbraad/.minishift                                                                                                                                                                                                                                                            
(minishift) Calling .GetSSHUsername                                                                                                                                                                                                                                                                                        
Using SSH client type: external                                                                                                                                                                                                                                                                                            
Using SSH private key: /home/gbraad/.minishift/machines/minishift/id_rsa (-rw-------)                                                                                                                                                                                                                                      
&{[-F /dev/null -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none docker@192.168.42.13 -o IdentitiesOnly=yes -i /home/gbraad/.minishift/machines/minishift/id_rsa -p 22] /usr
/bin/ssh <nil>}                                                                                                                                                                                                                                                                                                            
About to run SSH command:                                                                                                                                                                                                                                                                                                  
sudo systemctl daemon-reload                                                                                                                                                                                                                                                                                               
SSH cmd err, output: <nil>:                                                                                                                                                                                                                                                                                                
(minishift) Calling .GetSSHHostname                                                                                                                                                                                                                                                                                        
(minishift) DBG | GetIP called for minishift                                                                                                                                                                                                                                                                               
(minishift) DBG | Failed to retrieve dnsmasq leases from /var/lib/libvirt/dnsmasq/docker-machines.leases                                                                                                                                                                                                                   
(minishift) Calling .GetSSHPort                                                                                                                                                                                                                                                                                            
(minishift) DBG | IP address: 192.168.42.13                                                                                                                                                                                                                                                                                
(minishift) DBG | Unable to locate IP address for MAC 52:54:00:2f:1d:b3                                                                                                                                                                                                                                                    
(minishift) Calling .GetSSHKeyPath                                                                                                                                                                                                                                                                                         
(minishift) DBG | AK: resolvestorepath: /home/gbraad/.minishift                                                                                                                                                                                                                                                            
(minishift) Calling .GetSSHKeyPath                                                                                                                                                                                                                                                                                         
(minishift) Calling .GetSSHUsername                                                                                                                                                                                                                                                                                        
(minishift) DBG | AK: resolvestorepath: /home/gbraad/.minishift                                                                                                                                                                                                                                                            
Using SSH client type: external                                                                                                                                                                                                                                                                                            
Using SSH private key: /home/gbraad/.minishift/machines/minishift/id_rsa (-rw-------)                                                                                                                                                                                                                                      
&{[-F /dev/null -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none docker@192.168.42.13 -o IdentitiesOnly=yes -i /home/gbraad/.minishift/machines/minishift/id_rsa -p 22] /usr
/bin/ssh <nil>}                                                                                                                                                                                                                                                                                                            
About to run SSH command:                                                                                                                                                                                                                                                                                                  
sudo systemctl -f start docker                                                                                                                                                                                                                                                                                             
.SSH cmd err, output: exit status 1: Job for docker.service failed because the control process exited with error code.                                                                                                                                                                                                     
See "systemctl status docker.service" and "journalctl -xe" for details.                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                           
 FAIL E0619 03:58:23.116531   65547 start.go:392] Error starting the VM: Error creating the VM. Error creating machine: Error running provisioning: ssh command error:                                                                                                                                                     
command : sudo systemctl -f start docker                                                                                                                                                                                                                                                                                   
err     : exit status 1                                                                                                                                                                                                                                                                                                    
output  : Job for docker.service failed because the control process exited with error code.                                                                                                                                                                                                                                
See "systemctl status docker.service" and "journalctl -xe" for details.
. Retrying.                                                                              
Error starting the VM: Error creating the VM. Error creating machine: Error running provisioning: ssh command error:
command : sudo systemctl -f start docker
err     : exit status 1                    
output  : Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
                                                   
```

**Comment by gbraad** [comment]
```
[docker@minishift ~]$ sudo journalctl -u docker           
-- Logs begin at Mon 2018-06-18 23:57:57 EDT, end at Tue 2018-06-19 00:15:31 EDT. --
Jun 18 23:58:07 localhost systemd[1]: Starting Docker Application Container Engine...
Jun 18 23:58:08 localhost minishift-cert-gen[881]: Generating RSA private key, 2048 bit long modulus
Jun 18 23:58:08 localhost minishift-cert-gen[881]: ..............................................................................+++
Jun 18 23:58:08 localhost minishift-cert-gen[881]: ............................................+++
Jun 18 23:58:08 localhost minishift-cert-gen[881]: e is 65537 (0x010001)
Jun 18 23:58:08 localhost minishift-cert-gen[881]: problems making Certificate Request
Jun 18 23:58:08 localhost minishift-cert-gen[881]: 140177601357632:error:0D07A098:asn1 encoding routines:ASN1_mbstring_ncopy:string too short:crypto/asn1/a_mbstr.c:102:minsize=2
Jun 18 23:58:08 localhost minishift-cert-gen[881]: Generating RSA private key, 2048 bit long modulus
Jun 18 23:58:08 localhost minishift-cert-gen[881]: ..+++
Jun 18 23:58:08 localhost minishift-cert-gen[881]: ........................................+++
Jun 18 23:58:08 localhost minishift-cert-gen[881]: e is 65537 (0x010001)
Jun 18 23:58:08 localhost minishift-cert-gen[881]: x509: Cannot open input file ca.pem, No such file or directory
Jun 18 23:58:08 localhost minishift-cert-gen[881]: x509: Use -help for summary.
Jun 18 23:58:08 localhost minishift-cert-gen[881]: Generating RSA private key, 2048 bit long modulus
Jun 18 23:58:08 localhost minishift-cert-gen[881]: .........................+++
Jun 18 23:58:08 localhost minishift-cert-gen[881]: ..................+++
Jun 18 23:58:08 localhost minishift-cert-gen[881]: e is 65537 (0x010001)
Jun 18 23:58:08 localhost minishift-cert-gen[881]: x509: Cannot open input file ca.pem, No such file or directory
Jun 18 23:58:08 localhost minishift-cert-gen[881]: x509: Use -help for summary.
Jun 18 23:58:08 localhost minishift-cert-gen[881]: mv: cannot stat 'ca.pem': No such file or directory
Jun 18 23:58:08 localhost minishift-cert-gen[881]: mv: cannot stat 'server.pem': No such file or directory
Jun 18 23:58:08 localhost minishift-cert-gen[881]: cp: cannot stat '/etc/docker/ca.pem': No such file or directory
Jun 18 23:58:08 localhost minishift-cert-gen[881]: mv: cannot stat 'cert.pem': No such file or directory
Jun 18 23:58:08 localhost minishift-cert-gen[881]: chmod: cannot access '/home/docker/.docker/ca.pem': No such file or directory
Jun 18 23:58:08 localhost minishift-cert-gen[881]: chmod: cannot access '/home/docker/.docker/cert.pem': No such file or directory
Jun 18 23:58:08 localhost minishift-cert-gen[881]: chown: cannot access '/home/docker/.docker/ca.pem': No such file or directory
Jun 18 23:58:08 localhost minishift-cert-gen[881]: chown: cannot access '/home/docker/.docker/cert.pem': No such file or directory
Jun 18 23:58:08 localhost minishift-cert-gen[881]: chmod: cannot access '/etc/docker/ca.pem': No such file or directory
Jun 18 23:58:08 localhost minishift-cert-gen[881]: failed to change mode of '/etc/docker/ca.pem' from 0000 (---------) to 0000 (---------)
Jun 18 23:58:08 localhost minishift-cert-gen[881]: chmod: cannot access '/etc/docker/server.pem': No such file or directory
Jun 18 23:58:08 localhost minishift-cert-gen[881]: failed to change mode of '/etc/docker/server.pem' from 0000 (---------) to 0000 (---------)
Jun 18 23:58:08 localhost minishift-cert-gen[881]: mode of '/etc/docker/server-key.pem' changed from 0600 (rw-------) to 0400 (r--------)
Jun 18 23:58:09 localhost dockerd-current[930]: time="2018-06-18T23:58:09.933693123-04:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Jun 18 23:58:09 localhost dockerd-current[930]: time="2018-06-18T23:58:09.934972647-04:00" level=warning msg="Your kernel does not support cgroup rt period"
Jun 18 23:58:09 localhost dockerd-current[930]: time="2018-06-18T23:58:09.935042339-04:00" level=warning msg="Your kernel does not support cgroup rt runtime"
Jun 18 23:58:09 localhost dockerd-current[930]: time="2018-06-18T23:58:09.935470210-04:00" level=info msg="Loading containers: start."
Jun 18 23:58:10 localhost dockerd-current[930]: time="2018-06-18T23:58:10.082182582-04:00" level=info msg="Firewalld running: false"
Jun 18 23:58:10 localhost dockerd-current[930]: time="2018-06-18T23:58:10.263090178-04:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Jun 18 23:58:10 localhost.localdomain dockerd-current[930]: time="2018-06-18T23:58:10.376090339-04:00" level=info msg="Loading containers: done."
Jun 18 23:58:10 localhost.localdomain dockerd-current[930]: time="2018-06-18T23:58:10.595760303-04:00" level=warning msg="failed to retrieve docker-init version: unknown output format: tini version 0.18.0\n"
Jun 18 23:58:10 localhost.localdomain dockerd-current[930]: time="2018-06-18T23:58:10.596375352-04:00" level=info msg="Daemon has completed initialization"
Jun 18 23:58:10 localhost.localdomain dockerd-current[930]: time="2018-06-18T23:58:10.596446105-04:00" level=info msg="Docker daemon" commit=63758e0-unsupported graphdriver=overlay2 version=1.13.1
Jun 18 23:58:10 localhost.localdomain systemd[1]: Started Docker Application Container Engine.
Jun 18 23:58:10 localhost.localdomain dockerd-current[930]: time="2018-06-18T23:58:10.819652321-04:00" level=info msg="API listen on /var/run/docker.sock"
Jun 18 23:58:16 minishift dockerd-current[930]: time="2018-06-18T23:58:16.545375660-04:00" level=info msg="Processing signal 'terminated'"
Jun 18 23:58:16 minishift systemd[1]: Stopping Docker Application Container Engine...
Jun 18 23:58:16 minishift systemd[1]: Stopped Docker Application Container Engine.
Jun 18 23:58:19 minishift systemd[1]: Starting Docker Application Container Engine...
Jun 18 23:58:19 minishift dockerd-current[1482]: Failed to connect to containerd. Please make sure containerd is installed in your PATH or you have specified the correct address. Got error: exec: "docker-containerd": executable file not found in $PATH
Jun 18 23:58:19 minishift systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Jun 18 23:58:19 minishift systemd[1]: docker.service: Failed with result 'exit-code'.
Jun 18 23:58:19 minishift systemd[1]: Failed to start Docker Application Container Engine.
Jun 18 23:59:53 minishift systemd[1]: Starting Docker Application Container Engine...
Jun 18 23:59:53 minishift dockerd-current[1566]: Failed to connect to containerd. Please make sure containerd is installed in your PATH or you have specified the correct address. Got error: exec: "docker-containerd": executable file not found in $PATH
Jun 18 23:59:53 minishift systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Jun 18 23:59:53 minishift systemd[1]: docker.service: Failed with result 'exit-code'.
Jun 18 23:59:53 minishift systemd[1]: Failed to start Docker Application Container Engine.
[docker@minishift ~]$ 
```

This looks a lot like the issues with the certifcates I had before on CentOS

**Comment by gbraad** [comment]
`cat /etc/sysconfig/docker` does exist and therefore `$DOCKER_CERT_PATH` has a value.
However, the script upon running seems to error with `/home/docker/.docker/`
The cert path is `/etc/docker/`...

**Comment by praveenkumar** [comment]
```
$ ./minishift start --iso-url file:///home/prkumar/work/github/minishift-fedora-iso/build/minishift-fedora.iso
-- Starting profile 'minishift'
-- Check if depereccated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.9.0' is valid ... SKIP
-- Checking if requested OpenShift version 'v3.9.0' is supported ... SKIP
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present ... OK
-- Checking if Libvirt default network is active ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting local OpenShift cluster using 'kvm' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ................ OK
-- Checking for IP address ... OK
-- Checking for nameservers ... OK
-- Checking if external host is reachable from the Minishift VM ... 
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ... 
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 1% used OK
-- OpenShift cluster will be configured with ...
   Version: v3.9.0
-- Copying oc binary from the OpenShift container image to VM ....................... OK
-- Starting OpenShift cluster .........................
Using nsenter mounter for OpenShift volumes
Using public hostname IP 192.168.42.173 as the host IP
Using 192.168.42.173 as the server IP
Starting OpenShift using openshift/origin:v3.9.0 ...
OpenShift server started.

The server is accessible via web console at:
    https://192.168.42.173:8443

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin


[prkumar@local bin]$ ./minishift ssh
[docker@minishift ~]$ cat /etc/redhat-release 
Fedora release 28 (Twenty Eight)

```

**Pull request merged**
